import { createBrowserRouter, Navigate } from 'react-router'
import { RouteError } from './app/RouteError'
import { RootLayout } from './app/layouts/RootLayout'
import { LandingScreen } from './features/website/LandingScreen'
import { NotFoundScreen } from './features/website/NotFoundScreen'
import { LegalScreen } from './features/legal/LegalScreen'
import { LoadingState } from './ui/LoadingState'

export const router = createBrowserRouter([
  {
    element: <RootLayout />,
    errorElement: <RouteError />,
    hydrateFallbackElement: <LoadingState fullScreen title="Opening Stowaway…" description="Getting the app ready for your next trip." />,
    children: [
      { path: '/', element: <LandingScreen /> },
      { path: '/privacy', element: <LegalScreen policy="privacy" /> },
      { path: '/terms', element: <LegalScreen policy="terms" /> },
      { path: '/app', lazy: () => import('./features/onboarding/WelcomeScreen').then((m) => ({ Component: m.StartScreen })) },
      { path: '/quiz', lazy: () => import('./features/onboarding/QuizScreen').then((m) => ({ Component: m.QuizScreen })) },
      { path: '/new', lazy: () => import('./features/trips/CreateTripScreen').then((m) => ({ Component: m.CreateTripScreen })) },
      { path: '/inspire', lazy: () => import('./features/stowie/StowieScreen').then((m) => ({ Component: m.StowieScreen })) },
      { path: '/inspire/manual', lazy: () => import('./features/discovery/DiscoveryScreen').then((m) => ({ Component: m.DiscoveryScreen })) },
      { path: '/join', lazy: () => import('./features/trips/JoinScreen').then((m) => ({ Component: m.JoinScreen })) },
      { path: '/signin', lazy: () => import('./features/account/EmailSignInScreen').then((m) => ({ Component: m.EmailSignInScreen })) },
      { path: '/auth/callback', lazy: () => import('./features/account/AuthCallbackScreen').then((m) => ({ Component: m.AuthCallbackScreen })) },
      { path: '/oauth/consent', lazy: () => import('./features/account/ConnectorConsentScreen').then((m) => ({ Component: m.ConnectorConsentScreen })) },
      { path: '/connections', lazy: () => import('./features/account/ConnectedAppsScreen').then((m) => ({ Component: m.ConnectedAppsScreen })) },
      { path: '/t/:tripId/who', lazy: () => import('./features/trips/WhoScreen').then((m) => ({ Component: m.WhoScreen })) },
      {
        path: '/t/:tripId',
        lazy: () => import('./app/layouts/TripLayout').then((m) => ({ Component: m.TripLayout })),
        children: [
          { index: true, element: <Navigate to="overview" replace /> },
          { path: 'overview', lazy: () => import('./features/trips/TripOverviewScreen').then((m) => ({ Component: m.TripOverviewScreen })) },
          { path: 'travelers/:memberId', lazy: () => import('./features/trips/TravelerScreen').then((m) => ({ Component: m.TravelerScreen })) },
          { path: 'activity', lazy: () => import('./features/activity/ActivityScreen').then((m) => ({ Component: m.ActivityScreen })) },
          { path: 'map', lazy: () => import('./features/map/MapScreen').then((m) => ({ Component: m.default })) },
          { path: 'plan', lazy: () => import('./features/itinerary/PlanScreen').then((m) => ({ Component: m.PlanScreen })) },
          { path: 'plan/new', lazy: () => import('./features/itinerary/ItemFormScreen').then((m) => ({ Component: m.ItemFormScreen })) },
          { path: 'plan/:itemId', lazy: () => import('./features/itinerary/ItemDetailScreen').then((m) => ({ Component: m.ItemDetailScreen })) },
          { path: 'plan/:itemId/edit', lazy: () => import('./features/itinerary/ItemFormScreen').then((m) => ({ Component: m.ItemFormScreen })) },
          { path: 'tickets', lazy: () => import('./features/tickets/TicketsScreen').then((m) => ({ Component: m.TicketsScreen })) },
          { path: 'tickets/new', lazy: () => import('./features/tickets/TicketFormScreen').then((m) => ({ Component: m.TicketFormScreen })) },
          { path: 'tickets/:attachmentId', lazy: () => import('./features/tickets/TicketViewerScreen').then((m) => ({ Component: m.TicketViewerScreen })) },
          { path: 'money', lazy: () => import('./features/money/MoneyScreen').then((m) => ({ Component: m.MoneyScreen })) },
          { path: 'money/new', lazy: () => import('./features/money/ExpenseFormScreen').then((m) => ({ Component: m.ExpenseFormScreen })) },
          { path: 'money/:expenseId', lazy: () => import('./features/money/ExpenseFormScreen').then((m) => ({ Component: m.ExpenseFormScreen })) },
          { path: 'more', lazy: () => import('./features/trips/MoreScreen').then((m) => ({ Component: m.MoreScreen })) },
          { path: 'more/ideas', lazy: () => import('./features/stowie/StowieScreen').then((m) => ({ Component: m.StowieScreen })) },
          { path: 'more/ideas/manual', lazy: () => import('./features/discovery/DiscoveryScreen').then((m) => ({ Component: m.DiscoveryScreen })) },
          { path: 'more/tasks', lazy: () => import('./features/tasks/TasksScreen').then((m) => ({ Component: m.TasksScreen })) },
          { path: 'more/tasks/new', lazy: () => import('./features/tasks/TaskFormScreen').then((m) => ({ Component: m.TaskFormScreen })) },
          { path: 'more/tasks/:taskId', lazy: () => import('./features/tasks/TaskFormScreen').then((m) => ({ Component: m.TaskFormScreen })) },
          { path: 'more/packing', lazy: () => import('./features/packing/PackingScreen').then((m) => ({ Component: m.PackingScreen })) },
          { path: 'more/packing/new', lazy: () => import('./features/packing/PackingFormScreen').then((m) => ({ Component: m.PackingFormScreen })) },
          { path: 'more/packing/:itemId', lazy: () => import('./features/packing/PackingFormScreen').then((m) => ({ Component: m.PackingFormScreen })) },
          { path: 'more/emergency', lazy: () => import('./features/emergency/EmergencyScreen').then((m) => ({ Component: m.EmergencyScreen })) },
          { path: 'more/emergency/edit', lazy: () => import('./features/emergency/EmergencyEditScreen').then((m) => ({ Component: m.EmergencyEditScreen })) },
          { path: 'more/emergency/numbers', lazy: () => import('./features/emergency/EmergencyEditScreen').then((m) => ({ Component: m.EmergencyNumbersScreen })) },
          { path: 'more/emergency/driver', lazy: () => import('./features/emergency/EmergencyScreen').then((m) => ({ Component: m.DriverScreen })) },
          { path: 'more/emergency/me', lazy: () => import('./features/emergency/EmergencyScreen').then((m) => ({ Component: m.MedicalScreen })) },
          { path: 'wrapped', lazy: () => import('./features/wrapped/WrappedScreen').then((m) => ({ Component: m.WrappedScreen })) },
          { path: 'more/places', lazy: () => import('./features/places/PlacesScreen').then((m) => ({ Component: m.PlacesScreen })) },
          { path: 'more/places/new', lazy: () => import('./features/places/PlaceFormScreen').then((m) => ({ Component: m.PlaceFormScreen })) },
          { path: 'more/places/:placeId', lazy: () => import('./features/places/PlaceDetailScreen').then((m) => ({ Component: m.PlaceDetailScreen })) },
          { path: 'more/places/:placeId/edit', lazy: () => import('./features/places/PlaceFormScreen').then((m) => ({ Component: m.PlaceFormScreen })) },
          { path: 'more/settings', lazy: () => import('./features/trips/SettingsScreen').then((m) => ({ Component: m.SettingsScreen })) },
          { path: 'more/vote', lazy: () => import('./features/polls/PollsScreen').then((m) => ({ Component: m.PollsScreen })) },
          { path: 'more/vote/:pollId', lazy: () => import('./features/polls/PollScreen').then((m) => ({ Component: m.PollScreen })) },
        ],
      },
      { path: '*', element: <NotFoundScreen /> },
    ],
  },
])
