-- Core schema: trips, members, device access, places, links.
--
-- Sync contract (see src/data/sync):
--   * ids are generated by clients (so rows can be created offline)
--   * updated_at is always set by the server clock; clients pull by it
--   * rows are never hard-deleted; deleted_at is a tombstone that cannot be cleared
--   * access = "this device joined the trip via its share link" (trip_devices)

create schema if not exists private;
grant usage on schema private to authenticated;

-- ─── Triggers ───────────────────────────────────────────────────────────────

create or replace function private.sync_guard() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at := clock_timestamp();
  if tg_op = 'UPDATE' then
    new.id := old.id;
    new.trip_id := old.trip_id;
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    if old.deleted_at is not null then
      new.deleted_at := old.deleted_at;
    end if;
  else
    new.created_at := clock_timestamp();
  end if;
  return new;
end $$;

-- trips has no trip_id column, so it gets its own guard.
create or replace function private.sync_guard_trip() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at := clock_timestamp();
  if tg_op = 'UPDATE' then
    new.id := old.id;
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    -- Only rotate_share_token() may change the token; it sets this transaction-local flag.
    if current_setting('trip_hub.rotating_token', true) is distinct from 'on' then
      new.share_token := old.share_token;
    end if;
    if old.deleted_at is not null then
      new.deleted_at := old.deleted_at;
    end if;
  else
    new.created_at := clock_timestamp();
  end if;
  return new;
end $$;

-- ─── Tables ─────────────────────────────────────────────────────────────────

create table public.trips (
  id uuid primary key,
  name text not null check (length(trim(name)) between 1 and 120),
  timezone text not null default 'America/Guatemala',
  start_date date,
  end_date date,
  base_currency char(3) not null default 'USD',
  local_currency char(3),
  route_factor_low numeric not null default 1.2,
  route_factor_high numeric not null default 1.6,
  bbox float8[],
  offline_pack jsonb,
  share_token text not null unique,
  settings jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid,
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.members (
  id uuid primary key,
  trip_id uuid not null references public.trips (id) on delete cascade,
  display_name text not null check (length(trim(display_name)) between 1 and 40),
  color text,
  avatar_emoji text,
  home_timezone text,
  auth_user_id uuid, -- hook for real accounts later
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid
);

-- One row per (trip, device). Anonymous sign-in gives each device a stable auth.uid().
create table public.trip_devices (
  trip_id uuid not null references public.trips (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  member_id uuid references public.members (id),
  device_label text,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (trip_id, user_id)
);
create index trip_devices_user_idx on public.trip_devices (user_id);

create table public.places (
  id uuid primary key,
  trip_id uuid not null references public.trips (id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 200),
  category text not null default 'other' check (category in (
    'flight', 'lodging', 'reservation', 'activity', 'food', 'drink',
    'sight', 'transport', 'shopping', 'other')),
  tags text[] not null default '{}',
  lat float8 check (lat between -90 and 90),
  lng float8 check (lng between -180 and 180),
  address text,
  area text,
  status text not null default 'shortlist' check (status in (
    'catalog', 'shortlist', 'planned', 'booked', 'visited', 'rejected')),
  notes text,
  phone text,
  website text,
  opening_hours text,
  external_ids jsonb not null default '{}',
  source text not null default 'manual' check (source in ('osm', 'manual', 'import', 'suggestion')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid
);

create table public.links (
  id uuid primary key,
  trip_id uuid not null references public.trips (id) on delete cascade,
  place_id uuid references public.places (id),
  item_id uuid,     -- itinerary_items (added in a later migration)
  expense_id uuid,  -- expenses (added in a later migration)
  url text not null check (url ~* '^https?://'),
  label text,
  kind text not null default 'other' check (kind in ('booking', 'menu', 'info', 'map', 'other')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid
);

create trigger sync_guard before insert or update on public.trips
  for each row execute function private.sync_guard_trip();

do $$
declare t text;
begin
  foreach t in array array['members', 'places', 'links'] loop
    execute format(
      'create trigger sync_guard before insert or update on public.%I
         for each row execute function private.sync_guard()', t);
    execute format('create index %I on public.%I (trip_id, updated_at)', t || '_sync_idx', t);
  end loop;
end $$;
create index trips_sync_idx on public.trips (updated_at);

-- ─── Access control ─────────────────────────────────────────────────────────

create or replace function private.has_trip_access(t uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.trip_devices
    where trip_id = t and user_id = (select auth.uid())
  )
$$;
revoke all on function private.has_trip_access(uuid) from public;
grant execute on function private.has_trip_access(uuid) to authenticated;

alter table public.trips enable row level security;
alter table public.members enable row level security;
alter table public.trip_devices enable row level security;
alter table public.places enable row level security;
alter table public.links enable row level security;

-- Trips are created only through create_trip(); members may read and edit them.
create policy trips_select on public.trips for select to authenticated
  using ((select private.has_trip_access(id)));
create policy trips_update on public.trips for update to authenticated
  using ((select private.has_trip_access(id)))
  with check ((select private.has_trip_access(id)));

-- A device can see its own joins, and which device claimed which member on its trips.
create policy trip_devices_select on public.trip_devices for select to authenticated
  using ((select private.has_trip_access(trip_id)));

do $$
declare t text;
begin
  foreach t in array array['members', 'places', 'links'] loop
    execute format($f$
      create policy %1$s_select on public.%1$I for select to authenticated
        using ((select private.has_trip_access(trip_id)));
      create policy %1$s_insert on public.%1$I for insert to authenticated
        with check ((select private.has_trip_access(trip_id)));
      create policy %1$s_update on public.%1$I for update to authenticated
        using ((select private.has_trip_access(trip_id)))
        with check ((select private.has_trip_access(trip_id)));
    $f$, t);
  end loop;
end $$;
-- No delete policies anywhere: deletes are soft (deleted_at).

-- ─── RPCs ───────────────────────────────────────────────────────────────────

create or replace function private.new_share_token() returns text
language sql volatile set search_path = '' as $$
  select translate(rtrim(encode(extensions.gen_random_bytes(16), 'base64'), '='), '+/', '-_')
$$;

-- Creates a trip plus the creator's member row, and links this device to both.
create or replace function public.create_trip(
  p_trip_id uuid,
  p_name text,
  p_timezone text,
  p_start_date date,
  p_end_date date,
  p_base_currency text,
  p_local_currency text,
  p_member_id uuid,
  p_member_name text,
  p_member_color text default null
) returns text
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_token text := private.new_share_token();
begin
  if v_uid is null then
    raise exception 'Not signed in' using errcode = '28000';
  end if;
  insert into public.trips (id, name, timezone, start_date, end_date, base_currency,
                            local_currency, share_token, created_by, updated_by)
  values (p_trip_id, p_name, p_timezone, p_start_date, p_end_date, upper(p_base_currency),
          upper(nullif(p_local_currency, '')), v_token, p_member_id, p_member_id);
  insert into public.members (id, trip_id, display_name, color, created_by, updated_by)
  values (p_member_id, p_trip_id, p_member_name, p_member_color, p_member_id, p_member_id);
  insert into public.trip_devices (trip_id, user_id, member_id)
  values (p_trip_id, v_uid, p_member_id);
  return v_token;
end $$;

-- Exchanges a share token for access. Returns the trip id.
create or replace function public.join_trip(p_token text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_trip uuid;
begin
  if v_uid is null then
    raise exception 'Not signed in' using errcode = '28000';
  end if;
  select id into v_trip from public.trips
  where share_token = p_token and deleted_at is null;
  if v_trip is null then
    raise exception 'This trip link is invalid or has been replaced' using errcode = 'P0002';
  end if;
  insert into public.trip_devices (trip_id, user_id) values (v_trip, v_uid)
  on conflict (trip_id, user_id) do update set last_seen_at = now();
  return v_trip;
end $$;

-- "Who are you?" — ties this device to an existing member of the trip.
create or replace function public.claim_member(p_trip_id uuid, p_member_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.has_trip_access(p_trip_id) then
    raise exception 'No access to this trip' using errcode = '42501';
  end if;
  if not exists (select 1 from public.members
                 where id = p_member_id and trip_id = p_trip_id and deleted_at is null) then
    raise exception 'Unknown member' using errcode = 'P0002';
  end if;
  update public.trip_devices set member_id = p_member_id, last_seen_at = now()
  where trip_id = p_trip_id and user_id = auth.uid();
end $$;

-- "I'm new" — adds a member and claims it for this device.
create or replace function public.create_member_and_claim(
  p_trip_id uuid, p_member_id uuid, p_name text, p_color text default null
) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.has_trip_access(p_trip_id) then
    raise exception 'No access to this trip' using errcode = '42501';
  end if;
  insert into public.members (id, trip_id, display_name, color, created_by, updated_by)
  values (p_member_id, p_trip_id, p_name, p_color, p_member_id, p_member_id);
  update public.trip_devices set member_id = p_member_id, last_seen_at = now()
  where trip_id = p_trip_id and user_id = auth.uid();
end $$;

-- Invalidates the old link. Devices that already joined keep access.
create or replace function public.rotate_share_token(p_trip_id uuid) returns text
language plpgsql security definer set search_path = '' as $$
declare v_token text := private.new_share_token();
begin
  if not private.has_trip_access(p_trip_id) then
    raise exception 'No access to this trip' using errcode = '42501';
  end if;
  perform set_config('trip_hub.rotating_token', 'on', true);
  update public.trips set share_token = v_token where id = p_trip_id;
  perform set_config('trip_hub.rotating_token', 'off', true);
  return v_token;
end $$;

-- Keepalive target for the scheduled GitHub Action (prevents free-tier pausing).
create or replace function public.ping() returns timestamptz
language sql stable set search_path = '' as $$ select now() $$;

revoke execute on function
  public.create_trip(uuid, text, text, date, date, text, text, uuid, text, text),
  public.join_trip(text),
  public.claim_member(uuid, uuid),
  public.create_member_and_claim(uuid, uuid, text, text),
  public.rotate_share_token(uuid)
from public, anon;
grant execute on function
  public.create_trip(uuid, text, text, date, date, text, text, uuid, text, text),
  public.join_trip(text),
  public.claim_member(uuid, uuid),
  public.create_member_and_claim(uuid, uuid, text, text),
  public.rotate_share_token(uuid)
to authenticated;
grant execute on function public.ping() to anon, authenticated;
revoke all on function private.new_share_token() from public;

-- ─── Realtime (used only as a "something changed, pull now" signal) ─────────

alter publication supabase_realtime add table public.trips, public.members, public.places, public.links;
